from pydantic import BaseModel, Field
from typing import Optional, List

class TicketCreate(BaseModel):
    client_ticket_id: str = Field(..., description="UUID generated by frontend")
    station_id: str = Field(..., description="Factory station identifier")
    serial_number: str = Field(..., description="Equipment serial number")
    description: str = Field(..., description="Defect description")
    created_at: str = Field(..., description="ISO creation timestamp")
    photo_url: Optional[str] = Field(None, description="Optional photo URL")

class TicketResponse(BaseModel):
    id: str = Field(..., description="MongoDB ObjectId string")
    client_ticket_id: str
    station_id: str
    serial_number: str
    description: str
    photo_url: Optional[str] = None
    created_at: str
    synced_at: str

class SyncRequest(BaseModel):
    tickets: List[TicketCreate] = Field(..., description="List of offline tickets to sync")

class SyncItemResult(BaseModel):
    client_ticket_id: str
    status: str = Field(..., description="'synced' | 'already_synced' | 'failed'")
    server_id: Optional[str] = None
    error: Optional[str] = None

class SyncResponse(BaseModel):
    results: List[SyncItemResult]
